// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CdrAuthServer.Repository.Migrations
{
    [DbContext(typeof(CdrAuthServer.Repository.Infrastructure.CdrAuthServerDatabaseContext))]
    [Migration("20260812121516_V007_UpdateGrantSeedDataWithDeterministicDates")]
    partial class V007_UpdateGrantSeedDataWithDeterministicDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.Client", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ClientIdIssuedAt")
                        .HasColumnType("bigint");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = "11111111-1111-1111-1111-111111111111",
                            ClientIdIssuedAt = 0L,
                            ClientName = "Software Product 1"
                        });
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.ClientClaims", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("ClientClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = "11111111-1111-1111-1111-111111111111",
                            ClaimType = "claim_type",
                            ClaimValue = "claim_value"
                        });
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.Grant", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrantType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Key");

                    b.ToTable("Grants");

                    b.HasData(
                        new
                        {
                            Key = "12345678-1234-1234-1234-111122223333",
                            ClientId = "c6327f87-687a-4369-99a4-eaacd3bb8210",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Data = "{\"refresh_token\":\"valid-refresh-token\",\"account_id\":[\"123\",\"456\",\"789\"]}",
                            ExpiresAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantType = "cdr_arrangement",
                            Scope = "bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read energy:billing:read energy:electricity.servicepoints.basic:read energy:electricity.servicepoints.detail:read energy:electricity.usage:read energy:gas.servicepoints.basic:read energy:gas.servicepoints.detail:read energy:gas.usage:read telephone:accounts.basic:read telephone:accounts.detail:read telephone:usage:read water:accounts.basic:read water:accounts.detail:read water:usage:read common:customer.basic:read common:customer.detail:read",
                            SubjectId = "customer1"
                        },
                        new
                        {
                            Key = "expired-refresh-token",
                            ClientId = "c6327f87-687a-4369-99a4-eaacd3bb8210",
                            CreatedAt = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            Data = "{\"response_type\":\"code\",\"CdrArrangementId\":\"87654321-4321-4321-4321-333344445555\"}",
                            ExpiresAt = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantType = "refresh_token",
                            Scope = "bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read",
                            SubjectId = "customer1"
                        },
                        new
                        {
                            Key = "valid-refresh-token",
                            ClientId = "c6327f87-687a-4369-99a4-eaacd3bb8210",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Data = "{\"response_type\":\"code\",\"CdrArrangementId\":\"12345678-1234-1234-1234-111122223333\"}",
                            ExpiresAt = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            GrantType = "refresh_token",
                            Scope = "bank:accounts.basic:read bank:accounts.detail:read bank:transactions:read energy:billing:read energy:electricity.servicepoints.basic:read energy:electricity.servicepoints.detail:read energy:electricity.usage:read energy:gas.servicepoints.basic:read energy:gas.servicepoints.detail:read energy:gas.usage:read telephone:accounts.basic:read telephone:accounts.detail:read telephone:usage:read water:accounts.basic:read water:accounts.detail:read water:usage:read common:customer.basic:read common:customer.detail:read",
                            SubjectId = "customer1"
                        });
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.SoftwareProduct", b =>
                {
                    b.Property<int>("SoftwareProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoftwareProductId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoftwareProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoftwareProductStatus")
                        .HasColumnType("int");

                    b.HasKey("SoftwareProductId");

                    b.HasIndex("ClientId");

                    b.ToTable("SoftwareProducts");

                    b.HasData(
                        new
                        {
                            SoftwareProductId = 1,
                            ClientId = "11111111-1111-1111-1111-111111111111",
                            SoftwareProductDescription = "Software Product 1 Description",
                            SoftwareProductName = "Software Product 1",
                            SoftwareProductStatus = 1
                        },
                        new
                        {
                            SoftwareProductId = 2,
                            ClientId = "22222222-2222-2222-2222-222222222222",
                            SoftwareProductDescription = "Software Product 2 Description",
                            SoftwareProductName = "Software Product 2",
                            SoftwareProductStatus = 1
                        });
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.Token", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Data")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokenType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.ClientClaims", b =>
                {
                    b.HasOne("CdrAuthServer.Repository.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CdrAuthServer.Repository.Entities.SoftwareProduct", b =>
                {
                    b.HasOne("CdrAuthServer.Repository.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
