<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkVersion)</TargetFramework>
    <Version>$(Version)</Version>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>d57d2c28-46ab-4ea5-9327-daba2552a167</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>bin\$(MSBuildProjectName).xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>$(NoWarn);1591;1516</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>$(NoWarn);1591;1516</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Samples\**" />
    <Content Remove="Samples\**" />
    <EmbeddedResource Remove="Samples\**" />
    <None Remove="Samples\**" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Certificates\es256-private.pfx" />
    <None Remove="Certificates\ps256-private.pfx" />
    <None Remove="Certificates\tls-server.pfx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Certificates\es256-private.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Certificates\ps256-private.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Certificates\tls-server.pfx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="jose-jwt" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="Serilog.Sinks.OpenTelemetry">
      <TreatAsUsed>true</TreatAsUsed>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers.Unstable">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CdrAuthServer.API.Logger\CdrAuthServer.API.Logger.csproj" />
    <ProjectReference Include="..\CdrAuthServer.Infrastructure\CdrAuthServer.Infrastructure.csproj" />
    <ProjectReference Include="..\CdrAuthServer.Repository\CdrAuthServer.Repository.csproj" />
  </ItemGroup>
</Project>