# The "standalone" CdrAuthServer has no gateways. 
# This image is used by the Conformance Test Suite and "standalone" CdrAuthServer is also embedded into MDH/MDHE.

###############################################################################
# Build base layer
###############################################################################
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base

# Install nodejs, npm and live-server, which are needed by the auth UI
RUN apt-get update && apt-get install -y --no-install-recommends \
    nodejs \
    npm \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# install now so it will be immediately available for supervisord
RUN npm install -g react-inject-env

WORKDIR /app
EXPOSE 8080
EXPOSE 8001
EXPOSE 3000
ENV ASPNETCORE_ENVIRONMENT=Release

###############################################################################
# Build CdrAuthServer UI layer
###############################################################################
FROM node:24-alpine AS ui-build
WORKDIR /app

ARG target_environment=production
ENV PATH=/app/node_modules/.bin:$PATH

COPY CdrAuthServer.UI/package.json package.json
COPY CdrAuthServer.UI/package-lock.json package-lock.json
COPY CdrAuthServer.UI/.env.${target_environment} .env.${target_environment}
RUN npm ci

COPY CdrAuthServer.UI/. .
RUN npm run build

# Copy nginx config to container.
COPY CdrAuthServer.UI/nginx/nginx_auth_ui.conf /etc/nginx/conf.d/default.conf
COPY CdrAuthServer.UI/nginx/nginx.gzip.conf /etc/nginx/conf.d/gzip.conf

# Copy nginx SSL certificates to container.
RUN mkdir -p /etc/nginx/ssl
COPY CdrAuthServer.UI/nginx/ssl/authserver-ui.crt /etc/nginx/ssl/authserver-ui.crt
COPY CdrAuthServer.UI/nginx/ssl/authserver-ui.key /etc/nginx/ssl/authserver-ui.key

###############################################################################
# Build CdrAuthServer API layer
###############################################################################
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
COPY ./ .

FROM build AS publish
COPY ./Directory.Build.props /app/Directory.Build.props
COPY ./Directory.Packages.props /app/Directory.Packages.props
COPY ./.editorconfig /app/.editorconfig
COPY ./CdrAuthServer.Domain/. /app/CdrAuthServer.Domain
COPY ./CdrAuthServer.Repository/. /app/CdrAuthServer.Repository
COPY ./CdrAuthServer/. /app/CdrAuthServer
COPY ./CdrAuthServer.Infrastructure/. /app/CdrAuthServer.Infrastructure
COPY ./CdrAuthServer.API.Logger/. /app/CdrAuthServer.API.Logger

WORKDIR /app/CdrAuthServer
RUN dotnet publish -c Release -o /app/publish/cdrauthserver

COPY supervisord.standalone.conf /app/publish/supervisord.standalone.conf

###############################################################################
# Build final layer
###############################################################################
FROM base AS final
WORKDIR /app

# Auth UI #####################################################################
COPY --from=ui-build /app/build /usr/share/nginx/html/ui

# Copy build files to nginx output folder.
COPY --from=ui-build /app/build /usr/share/nginx/html/ui
COPY --from=ui-build /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY --from=ui-build /etc/nginx/conf.d/gzip.conf /etc/nginx/conf.d/gzip.conf
COPY --from=ui-build /etc/nginx/ssl/authserver-ui.crt /etc/nginx/ssl/authserver-ui.crt
COPY --from=ui-build /etc/nginx/ssl/authserver-ui.key /etc/nginx/ssl/authserver-ui.key



# Auth API ####################################################################
COPY --from=publish /app/publish/supervisord.standalone.conf .
COPY --from=publish /app/publish/cdrauthserver ./cdrauthserver

RUN apt-get update && apt-get install -y supervisor
RUN apt-get update && apt-get install -y sudo

# Install wget for use in health checks
RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

USER 0
RUN setcap cap_net_bind_service=+ep /usr/sbin/nginx

# Run as non-root user
RUN chown -R app:app /app \
&& chown -R app:app /var/log/nginx \
&& chown -R app:app /var/lib/nginx \
&& touch /run/nginx.pid \
&& chown -R app:app /run/nginx.pid \
&& touch /usr/share/nginx/html/ui/env.js \
&& chown -R app:app /usr/share/nginx/html/ui/env.js
 
USER app

ENV ASPNETCORE_URLS=https://+:8001;http://+:8080

# Entry point #################################################################
ENTRYPOINT ["/usr/bin/supervisord", "-c", "/app/supervisord.standalone.conf"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]