# Dockerfile for E2E tests

# NB: Ensure playwright version used in the ConsumerDataRight.ParticipantTooling.Shared.TestAutomation NuGet package and base image below are same (ie currently 1.43.0)
# Playwright jammy for .Net 8
FROM mcr.microsoft.com/playwright/dotnet:v1.43.0-jammy as build

###############################################################################
# Build E2E tests
###############################################################################
WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Build tests
WORKDIR /src/CdrAuthServer.E2ETests
ARG FEED_ACCESSTOKEN
ARG FEED_URI
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URI}\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"
RUN echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

RUN dotnet restore
RUN dotnet build --configuration Release

###############################################################################
# Run E2E tests
###############################################################################
ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "--results-directory", "/testresults"]
