# Dockerfile for running unit tests

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

RUN curl -L https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh  | sh

# Copy source
COPY . ./

# Intall CA certificates
RUN apt-get update && apt-get install -y sudo
RUN sudo cp ./CdrAuthServer.mTLS.Gateway/Certificates/ca.crt /usr/local/share/ca-certificates/ca.crt \
    && sudo update-ca-certificates

# Build tests
WORKDIR /src
ARG FEED_ACCESSTOKEN
ARG FEED_URI
ENV VSS_NUGET_EXTERNAL_FEED_ENDPOINTS="{\"endpointCredentials\": [{\"endpoint\":\"${FEED_URI}\", \"username\":\"docker\", \"password\":\"${FEED_ACCESSTOKEN}\"}]}"
RUN echo $VSS_NUGET_EXTERNAL_FEED_ENDPOINTS

RUN dotnet restore CdrAuthServer.sln
RUN dotnet build CdrAuthServer.sln --configuration Release

# Run tests
ENTRYPOINT ["dotnet", "test", "CdrAuthServer.sln", "--configuration", "Release", "--filter", "UnitTests", "--no-build", "--logger", "trx;verbosity=detailed", "--results-directory", "/testresults"]