# Dockerfile for running unit tests

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Build tests
WORKDIR /src
RUN dotnet build --configuration Release

# Run tests
ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--filter", "UnitTests", "--no-build", "--logger", "trx;verbosity=detailed", "-r", "/testresults"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
