# Dockerfile for running integration tests

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Run tests
WORKDIR /src/CdrAuthServer.IntegrationTests
# RUN dotnet build
RUN dotnet build --configuration Release

ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
# ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--filter", "US44264_CdrAuthServer_JARM", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
