# Dockerfile for E2E tests

# NB: Ensure playwright version used in CDR.SandboxManagement.E2ETests and base image below are same (ie currently 1.26.0)
FROM mcr.microsoft.com/playwright/dotnet:v1.26.0-focal as build

###############################################################################
# Build E2E tests
###############################################################################
WORKDIR /src
EXPOSE 9999
EXPOSE 9998
EXPOSE 9997
EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Build tests
WORKDIR /src/CdrAuthServer.E2ETests
RUN dotnet build --configuration Release

###############################################################################
# Run E2E tests
###############################################################################
ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
# ENTRYPOINT ["tail", "-f", "/dev/null"]
