# Docker compose e2e tests

services:
  mock-register:
    container_name: mock-register
    image: mock-register
    hostname: mock-register
    ports: 
      - "7000:7000"
      - "7001:7001"
      - "7006:7006"
    extra_hosts:
      - "cdr-auth-server-e2e-tests:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    # NOTE - commented out volumes below as volume is mounted as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops container from starting because of different user
    # volumes:
    #   - "./_temp/mock-register/tmp:/tmp"      
    healthcheck:
      test: wget --no-check-certificate --no-verbose --spider https://localhost:7006/health || exit 1
      timeout: 5s
      interval: 5s
      retries: 50      
    depends_on:
      mssql:
        condition: service_healthy

  cdr-auth-server:
    container_name: cdr-auth-server-standalone
    image: cdr-auth-server-standalone
    build:
      context: .
      dockerfile: Dockerfile.standalone
    ports:
      - "8001:8001"
      - "3000:3000"    
    extra_hosts:
      - "cdr-auth-server-e2e-tests:host-gateway"
    environment:
      - ASPNETCORE_ENVIRONMENT=Release.Standalone
      # tests need expiry of 3600
      - CdrAuthServer__AccessTokenExpirySeconds=3600
      - CdrAuthServer__SupportJarmEncryption=false
      # we are testing UI so don't run in headless mode
      - CdrAuthServer__HeadlessMode=false
      #############################################################################################
      - REACT_APP_DATA_FILE_NAME=customer-seed-data.json
      - REACT_APP_CLUSTER_DATA_FILE_NAME=cluster-seed-data.json
      - REACT_APP_DEFAULT_USER_NAME_TEXT=jwilson, ksmith
      - REACT_APP_CDR_POLICY_LINK=https://cdr-policy
      - REACT_APP_JWKS_URI=https://cdr-auth-server:8001/.well-known/openid-configuration/jwks
      #############################################################################################
    # NOTE - commented out volumes below as volume is mounted as 1001:121 (vsts:docker) in build pipeline and causes issue with chown in dockerfile (appuser:appgroup), ie stops container from starting because of different user
    # volumes:
    #   - "./_temp/cdr-auth-server-standalone/tmp:/tmp"      
    healthcheck:
      test: ((wget --no-check-certificate --no-verbose --spider https://localhost:8001/health) && (wget --no-check-certificate --no-verbose --spider http://localhost:3000)) || exit 1      
      timeout: 5s
      interval: 5s
      retries: 50
    depends_on:
      mssql:
        condition: service_healthy
      mock-register:
        condition: service_healthy

  cdr-auth-server-e2e-tests:
    container_name: cdr-auth-server-e2e-tests
    image: cdr-auth-server-e2e-tests
    ports: 
      - "9999:9999"
      - "9998:9998"
      - "9997:9997"
      - "9996:9996"
    build:
      context: .
      dockerfile: Dockerfile.e2e-tests
      args:
        FEED_URI: ${FEED_URI}
        FEED_ACCESSTOKEN: ${FEED_ACCESSTOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/cdr-auth-server-e2e-tests-standalone/testresults:/testresults"
    depends_on:
      mssql:
        condition: service_healthy
      cdr-auth-server:
        condition: service_healthy
      mock-register:
        condition: service_healthy

  mssql:
    container_name: sql1
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pa{}w0rd2019
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S . -U sa -P "Pa{}w0rd2019" -Q "SELECT 1" -No || exit 1
      timeout: 5s
      interval: 5s
      retries: 20
