# Docker compose to run unit tests in the build pipeline

services:
  cdr-auth-server-unit-tests:
    container_name: cdr-auth-server-unit-tests
    image: cdr-auth-server-unit-tests
    build:
      context: .
      dockerfile: Dockerfile.unit-tests
      args:
        FEED_URI: ${FEED_URI}
        FEED_ACCESSTOKEN: ${FEED_ACCESSTOKEN}
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    volumes:
      - "./_temp/cdr-auth-server-unit-tests/testresults:/testresults"      
