# Dockerfile for running GetDataRecipient integration tests

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
# EXPOSE 9999
# EXPOSE 9998
# EXPOSE 9997
# EXPOSE 9996

# Default ASPNETCORE_ENVIRONMENT to Release
ENV ASPNETCORE_ENVIRONMENT=Release

# Copy source
COPY . ./

# Install developer certificate
RUN dotnet dev-certs https 

# Run tests
WORKDIR /src/CdrAuthServer.GetDataRecipients.IntegrationTests
RUN dotnet build --configuration Release

ENTRYPOINT ["dotnet", "test", "--configuration", "Release", "--no-build", "--logger", "trx;verbosity=detailed;LogFileName=results.trx", "-r", "/testresults"]
