[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
childlogdir=/tmp

[program:CdrAuthServer]
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
directory=/app/cdrauthserver    
command=/usr/bin/dotnet /app/cdrauthserver/CdrAuthServer.dll

[program:CdrAuthServer-UI]
priority=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
directory=/usr/share/nginx/html/ui
command=bash -c "react-inject-env set -d /usr/share/nginx/html/ui && exec nginx -g 'daemon off;'"
autostart=true
autorestart=true
startretries=5
numprocs=1
startsecs=0

# [program:CdrAuthServer-UI]
# stdout_logfile=/dev/stdout
# stdout_logfile_maxbytes=0
# command=nginx -g 'daemon off;'
